<?php
/**
 * Model: the pricing page (/pricing/), rendered by page-templates/pricing.php.
 * Content copied word for word from the flat build's pricing.php. Every
 * figure on this page is a price Kulwant set: never change a number here
 * without his instruction.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }

$two = array( 'Label', 'Link' );

return array(
	'name'      => 'pricing',
	'post_type' => 'page',
	'template'  => 'page-templates/pricing.php',
	'label'     => 'Pricing page',
	'prefix'    => 'pg_pricing',
	'schema'    => array(
		'hero'  => array( 'group', 'Hero', array(
			'eyebrow' => array( 'text', 'Eyebrow' ),
			'h1'      => array( 'text', 'Headline' ),
			'sub'     => array( 'area', 'Subhead' ),
			'sub2'    => array( 'area', 'Second line' ),
			'btn'     => array( 'slots', 'Button', $two ),
			'link'    => array( 'slots', 'Quiet link', $two ),
		) ),
		'plansHead' => array( 'group', 'Plans: section head and labels', array(
			'eyebrow' => array( 'text', 'Eyebrow' ),
			'heading' => array( 'text', 'Heading' ),
			'per'     => array( 'text', 'After the price (e.g. "/ month")' ),
			'more'    => array( 'text', 'Open the full deliverables' ),
			'less'    => array( 'text', 'Close the full deliverables' ),
		) ),
		'plans' => array( 'blocks', 'Plans', array(
			'name'     => array( 'text', 'Plan name' ),
			'from'     => array( 'text', 'Before the price (e.g. "From"), empty for a fixed price' ),
			'price'    => array( 'text', 'Price', 'A price Kulwant set. Never change it without his instruction.' ),
			'line'     => array( 'area', 'Line' ),
			'who'      => array( 'area', 'Who it is for' ),
			'does'     => array( 'area', 'What we do' ),
			'inherits' => array( 'text', 'List label' ),
			'items'    => array( 'lines', 'What you get (one per line)' ),
			'foot'     => array( 'area', 'Note under the list' ),
			'cta'      => array( 'slots', 'Button', $two ),
			'full'     => array( 'blocks', 'Full deliverables', array(
				'head'  => array( 'text', 'Group heading' ),
				'lines' => array( 'lines', 'Deliverables (one per line)' ),
			) ),
		) ),
		'terms' => array( 'group', 'What the deliverables mean', array(
			'eyebrow' => array( 'text', 'Eyebrow' ),
			'heading' => array( 'text', 'Heading' ),
			'items'   => array( 'rows', 'Definitions', array( 'icon', 'Name', 'Text' ) ),
		) ),
		'setup' => array( 'group', 'Getting started', array(
			'heading'   => array( 'text', 'Heading' ),
			'label'     => array( 'text', 'Setup label' ),
			'lead'      => array( 'text', 'Setup price line' ),
			'paras'     => array( 'paras', 'Paragraphs' ),
			'listLabel' => array( 'text', 'List label' ),
			'list'      => array( 'lines', 'What setup includes (one per line)' ),
			'starts'    => array( 'rows', 'Ways to start', array( 'Flag (empty = no flag)', 'Name', 'Text' ) ),
		) ),
		'why'   => array( 'group', 'What you are paying for', array(
			'eyebrow' => array( 'text', 'Eyebrow' ),
			'heading' => array( 'text', 'Heading' ),
			'sub'     => array( 'area', 'Subhead' ),
			'lead'    => array( 'text', 'List lead' ),
			'ticks'   => array( 'lines', 'List (one per line)' ),
			'tail'    => array( 'area', 'Closing line' ),
		) ),
		'faq'   => array( 'group', 'Questions', array(
			'eyebrow' => array( 'text', 'Eyebrow' ),
			'heading' => array( 'text', 'Heading' ),
			'note'    => array( 'area', 'Note' ),
			'qs'      => array( 'qs', 'Questions' ),
		) ),
	),
	'items'     => array(
		'pricing' => array(
			'title' => 'Pricing',
			'seo'   => array(
				'Plans and pricing, from $750 a month | RankinAI',
				'Four plans, from $750 a month. What each one includes, what the deliverables mean, what setup covers, and the answers to the questions people ask before choosing.',
			),
			'data'  => array(
				'hero'      => array(
					'eyebrow' => 'Plans and pricing',
					'h1'      => 'Build the pipeline. Know the investment.',
					'sub'     => 'Choose the support that fits where your business is now, and the work you want to win next.',
					'sub2'    => 'Each plan brings together search, content, your website, reputation and follow-up, with paid advertising where it supports your goals.',
					'btn'     => array( 'Get your growth audit', '/growth-audit/' ),
					'link'    => array( 'Help me choose a plan', '/call/' ),
				),
				'plansHead' => array(
					'eyebrow' => 'Choose your plan',
					'heading' => 'Where does your business want to go next?',
					'per'     => '/ month',
					'more'    => 'Read full deliverables',
					'less'    => 'Hide full deliverables',
				),
				'plans'     => array(
					array(
						'name'     => 'Foundation',
						'from'     => '',
						'price'    => '$750',
						'line'     => 'Give your next client a clearer path to finding you.',
						'who'      => 'For small firms building a consistent marketing presence around a focused service offering and one location.',
						'does'     => 'We establish the essentials, strengthen your most important pages, and make it easier to capture and follow up on enquiries.',
						'inherits' => 'Your monthly plan includes',
						'items'    => array(
							'Search improvements focused on your priority services and local market.',
							'Google Business Profile management.',
							'AI visibility checks on an agreed set of buyer questions across two platforms.',
							'Two content pieces, such as service-page copy, an article or a client story.',
							'Targeted improvements to existing website pages and enquiry forms.',
							'Review-request process and priority business-profile updates.',
							'Basic enquiry tracking, an automatic acknowledgement and one follow-up sequence.',
							'Management of one Google Search campaign, when appropriate.',
							'A monthly report and one review call.',
						),
						'cta'      => array( 'Start with Foundation', '/growth-audit/' ),
						'full'     => array(
							array( 'head' => 'AI and search visibility', 'lines' => array(
								'Google Business Profile set up and optimised',
								'Local search for your service area',
								'Monthly technical SEO maintenance',
								'Answer-first blocks on your priority pages',
								'Visibility tracked on one or two AI assistants',
								'Monthly check of the prompts your buyers actually type',
							) ),
							array( 'head' => 'Content', 'lines' => array(
								'2 pieces a month: a success story, a project write-up, an article or a review asset',
								'Written from a half-hour interview, so nobody on your side has to draft anything',
							) ),
							array( 'head' => 'Website and conversion', 'lines' => array(
								'Core service pages improved: titles, meta, calls to action, proof blocks',
								'1 landing page built to convert',
								'Enquiry forms cut back to what you actually need',
								'Monthly on-page improvements to the priority pages',
							) ),
							array( 'head' => 'Reviews and reputation', 'lines' => array(
								'Review system set up: how you ask, where they land, where they show',
								'Your profiles claimed and corrected where the details are wrong',
							) ),
							array( 'head' => 'CRM and automation', 'lines' => array(
								'CRM set up',
								'Instant auto-reply to every new enquiry',
								'1 follow-up sequence',
								'A cleaner route from enquiry to booked conversation',
							) ),
							array( 'head' => 'Paid advertising', 'lines' => array(
								'1 Google search campaign managed. The spend is separate and stays in your account',
							) ),
							array( 'head' => 'Strategy and reporting', 'lines' => array(
								'Monthly performance report',
								'1 strategy call a month',
								'We tell you first if something breaks',
							) ),
						),
					),
					array(
						'name'     => 'Growth',
						'from'     => '',
						'price'    => '$1,250',
						'line'     => 'Build a stronger flow of opportunities around the work you want.',
						'who'      => 'For firms ready to develop their visibility, strengthen their proof and improve how enquiries become sales conversations.',
						'does'     => 'We expand the content and search work, support more deliberate campaigns, and improve qualification and follow-up.',
						'inherits' => 'Everything in Foundation, with',
						'items'    => array(
							'Broader search coverage across your agreed priority services.',
							'Four content pieces per month, including service or location-page copy where needed.',
							'AI visibility checks across up to four platforms.',
							'Regular updates to existing pages with improvement potential.',
							'Landing-page and enquiry-journey improvements within the agreed scope.',
							'Automated review requests and drafted review replies.',
							'Lead qualification and more tailored follow-up sequences.',
							'Management of up to two Google Search campaigns and one retargeting campaign.',
							'A monthly report and two review calls.',
						),
						'cta'      => array( 'Start with Growth', '/growth-audit/' ),
						'full'     => array(
							array( 'head' => 'AI and search visibility', 'lines' => array(
								'Broader topic coverage plus one service or area page',
								'Topic clusters started: a main page with supporting ones around it',
								'Google Business Profile set up and optimised',
								'Local search for your service area',
								'Answer-first blocks on your priority pages',
								'Visibility tracked on more AI assistants, checked monthly against the prompts your buyers type',
								'Monthly technical SEO maintenance',
							) ),
							array( 'head' => 'Content', 'lines' => array(
								'4 pieces a month: success stories, project write-ups, articles or review assets',
								'Monthly refreshes on the pages closest to moving',
								'Written from a half-hour interview, so nobody on your side has to draft anything',
							) ),
							array( 'head' => 'Website and conversion', 'lines' => array(
								'Core service pages improved: titles, meta, calls to action, proof blocks',
								'Extra landing pages beyond the first',
								'Monthly testing on the pages that carry enquiries',
								'Question and comparison sections where they help someone decide',
								'Enquiry forms cut back to what you actually need',
								'Monthly on-page improvements to the priority pages',
							) ),
							array( 'head' => 'Reviews and reputation', 'lines' => array(
								'Review system set up: how you ask, where they land, where they show',
								'Your profiles claimed and corrected where the details are wrong',
								'Requests sent automatically after the right moment in the job',
								'Replies drafted for you, including the difficult ones',
							) ),
							array( 'head' => 'CRM and automation', 'lines' => array(
								'CRM set up',
								'Instant auto-reply to every new enquiry',
								'Lead qualification built into the enquiry flow',
								'Email and WhatsApp follow-up sequences',
								'A cleaner route from enquiry to booked conversation',
							) ),
							array( 'head' => 'Paid advertising', 'lines' => array(
								'Google search plus retargeting',
								'The spend is separate and stays in your account',
							) ),
							array( 'head' => 'Strategy and reporting', 'lines' => array(
								'Monthly performance report plus 2 calls',
								'A dedicated specialist on your account',
								'We tell you first if something breaks',
							) ),
						),
					),
					array(
						'name'     => 'Accelerate',
						'from'     => '',
						'price'    => '$1,750',
						'line'     => 'Make your next stage of growth a coordinated effort.',
						'who'      => 'For established firms expanding selected services, entering additional locations, or pursuing higher-value work.',
						'does'     => 'We increase delivery, build stronger evidence around your expertise, and review performance more frequently.',
						'inherits' => 'Everything in Growth, with',
						'items'    => array(
							'A wider search and content plan across agreed services and locations.',
							'Six content pieces per month.',
							'More extensive updates to existing content and priority pages.',
							'Outreach to relevant publications and industry websites.',
							'A structured programme of website and enquiry-journey improvements.',
							'Conversion experiments where traffic and data support meaningful testing.',
							'More detailed lead routing, qualification and follow-up.',
							'Management of up to three Google Search campaigns and one retargeting campaign.',
							'Reviews every two weeks with a senior strategist.',
						),
						'cta'      => array( 'Start with Accelerate', '/growth-audit/' ),
						'full'     => array(
							array( 'head' => 'AI and search visibility', 'lines' => array(
								'Wide topic coverage plus multiple service and area pages',
								'Google Business Profile and local search for your service area',
								'Every major AI assistant covered, and the pages rewritten to be quotable by them',
								'Monthly check of the prompts your buyers actually type',
								'Authority building: quality mentions and links, partnerships, press angles',
								'Weekly Search Console monitoring',
								'Monthly technical SEO maintenance',
							) ),
							array( 'head' => 'Content', 'lines' => array(
								'6 pieces a month: success stories, project write-ups, articles or review assets',
								'Outreach for 2 placements a month: guest pieces, press mentions or industry publications, with the decision resting with the publisher',
								'8 existing articles refreshed a month',
								'Written from a half-hour interview, so nobody on your side has to draft anything',
							) ),
							array( 'head' => 'Website and conversion', 'lines' => array(
								'Core service pages improved: titles, meta, calls to action, proof blocks',
								'Landing pages built as the programme needs them',
								'Continuous testing across the whole journey, not just the enquiry form',
								'Layout changes made because a test said so',
								'Proof placed where people decide, rather than on a page nobody opens',
								'Enquiry forms cut back to what you actually need',
							) ),
							array( 'head' => 'Reviews and reputation', 'lines' => array(
								'Review system set up: how you ask, where they land, where they show',
								'Requests sent automatically after the right moment in the job',
								'Replies drafted for you, including the difficult ones',
								'Every platform your buyers check, covered and kept current',
								'Mentions of your name monitored, so you hear about them first',
							) ),
							array( 'head' => 'CRM and automation', 'lines' => array(
								'CRM set up, with an instant auto-reply to every new enquiry',
								'Lead qualification built into the enquiry flow',
								'Email and WhatsApp follow-up sequences',
								'Full follow-up automation, tuned every month',
								'Pipeline tracking, so you can see where enquiries stall',
							) ),
							array( 'head' => 'Paid advertising', 'lines' => array(
								'Multiple Google search campaigns plus retargeting',
								'The spend is separate and stays in your account',
							) ),
							array( 'head' => 'Strategy and reporting', 'lines' => array(
								'Reports and calls every two weeks',
								'A senior strategist on your account',
								'We tell you first if something breaks',
							) ),
						),
					),
					array(
						'name'     => 'Custom',
						'from'     => 'From',
						'price'    => '$2,500',
						'line'     => 'A plan built around a more complex business.',
						'who'      => 'For firms operating across several locations or markets, coordinating multiple teams, or needing a broader mix of channels and systems.',
						'does'     => 'We agree the scope around your commercial priorities, internal resources and reporting needs.',
						'inherits' => 'Your plan can include',
						'items'    => array(
							'Marketing across multiple locations or countries.',
							'Content and campaigns for several service lines.',
							'Additional advertising platforms, including LinkedIn and Meta.',
							'CRM integrations and more complex automation.',
							'Reporting by market, location or business unit.',
							'Specialist support alongside your internal marketing team.',
							'A tailored delivery schedule and review cadence.',
						),
						'foot'     => 'You receive a defined proposal with the deliverables, responsibilities and full price.',
						'cta'      => array( 'Discuss a Custom plan', '/call/' ),
						'full'     => array(
							array( 'head' => 'One-time setup', 'lines' => array(
								'Tracking set up properly: analytics, Search Console, and conversions on forms and calls',
								'Tracking split by location and by market, so you can see which ones are working',
								'Baseline report: where you rank, what traffic you get, what converts',
								'Full technical audit and fix plan: crawling and indexing, sitemap, redirects, canonicals, internal linking',
								'Competitor gap analysis and a page-mapping plan, run per market',
								'The questions your buyers ask, mapped to the pages that answer them',
								'The pages that establish who you are: about, process, results, and named people behind them',
								'Your name, address and phone number consistent everywhere they appear, for every location',
								'Full structured data across the site',
								'Custom reporting built around the numbers your board already looks at',
							) ),
							array( 'head' => 'AI and search visibility', 'lines' => array(
								'Wide topic coverage across every service you sell',
								'A page for each location and each service, rather than one page doing both jobs',
								'Google Business Profile and local search for every location',
								'Every major AI assistant covered, and the pages rewritten to be quotable by them',
								'AI visibility tracked per market, not as one average',
								'Authority building in every market you sell into: quality mentions and links, partnerships, press angles',
								'Weekly Search Console monitoring',
								'Monthly technical SEO maintenance',
							) ),
							array( 'head' => 'Content', 'lines' => array(
								'Volume set to the number of services and markets you cover',
								'Success stories, project write-ups, articles and review assets',
								'Outreach for placements on other sites: guest pieces, press mentions and industry publications',
								'Existing articles refreshed every month',
								'Written from a half-hour interview, so nobody on your side has to draft anything',
							) ),
							array( 'head' => 'Website and conversion', 'lines' => array(
								'Core service pages improved: titles, meta, calls to action, proof blocks',
								'Location and service landing pages built as the programme needs them',
								'Continuous testing across the whole journey, not just the enquiry form',
								'Layout changes made because a test said so',
								'Proof placed where people decide, rather than on a page nobody opens',
								'Enquiry forms cut back to what you actually need',
							) ),
							array( 'head' => 'Reviews and reputation', 'lines' => array(
								'Review system set up per location: how you ask, where they land, where they show',
								'Requests sent automatically after the right moment in the job',
								'Replies drafted for you, including the difficult ones',
								'Every platform your buyers check, covered and kept current',
								'One view of reviews across all locations, so you can compare them',
								'Mentions of your name monitored in every market',
							) ),
							array( 'head' => 'CRM and automation', 'lines' => array(
								'CRM set up, with an instant auto-reply to every new enquiry',
								'Lead qualification built into the enquiry flow',
								'Email and WhatsApp follow-up sequences',
								'Full follow-up automation, tuned every month',
								'Routing so an enquiry reaches the right office or team',
								'Integrations with the systems you already run',
								'Pipeline tracking, so you can see where enquiries stall',
							) ),
							array( 'head' => 'Paid advertising', 'lines' => array(
								'Multi-channel campaigns plus retargeting, sized to the budget',
								'Run per market, with budgets you can move between them',
								'The spend is separate and stays in your account',
							) ),
							array( 'head' => 'Strategy and reporting', 'lines' => array(
								'The reporting cadence you set',
								'A senior team on the account',
								'Quarterly planning against your own targets',
								'We tell you first if something breaks',
							) ),
							array( 'head' => 'How it is priced', 'lines' => array(
								'Scope and price quoted after the free audit and the strategy call',
								'Sized to your goals, your markets and your team, not to your logo',
							) ),
						),
					),
				),
				'terms'     => array(
					'eyebrow' => 'What the deliverables mean',
					'heading' => 'Clear scope makes a better working relationship.',
					'items'   => array(
						array( 'pencil', 'Content pieces',
							'A piece may be an article, a case study, or copy for a service or location page. We agree the format and brief in advance. A new page requiring design or development is scoped separately from its copy.' ),
						array( 'wrench', 'Website improvements',
							'These cover agreed changes to your existing pages, templates and enquiry journey. A full redesign, substantial development or a new integration receives its own scope and price.' ),
						array( 'target', 'Advertising campaigns',
							'Campaign management sits within the limits of your plan. The advertising budget is paid separately through your own accounts. We recommend channels and budgets based on the market you want to reach.' ),
						array( 'spark', 'AI visibility',
							'We check an agreed set of questions and record where your firm appears. The work supports your visibility. Inclusion in an AI answer cannot be guaranteed by anyone.' ),
						array( 'link', 'Outreach and placements',
							'Outreach covers research, pitching and follow-up. Publication decisions remain with the publisher, so editorial coverage and links are not guaranteed.' ),
						array( 'sliders', 'Your monthly priorities',
							'We agree how the work is distributed. If advertising is not appropriate, for example, your proposal explains how that capacity will support other priorities.' ),
					),
				),
				'setup'     => array(
					'heading'   => 'Set up once. Build from there.',
					'label'     => 'Initial setup',
					'lead'      => '$500, once.',
					'paras'     => array(
						'For Foundation, Growth and Accelerate, setup establishes the information and systems needed to begin the agreed plan.',
						'Substantial website repairs, CRM migrations, custom integrations and additional development are quoted separately. Custom-plan setup is scoped and priced in your proposal.',
					),
					'listLabel' => 'It includes',
					'list'      => array(
						'A kickoff session covering your goals, ideal clients and priority services.',
						'Review of the website, accounts and access required for delivery.',
						'A baseline of available search, traffic and enquiry data.',
						'Standard tracking setup or corrections for agreed enquiry actions.',
						'A review of your current lead-capture and follow-up process.',
						'An initial action plan with priorities and responsibilities.',
					),
					'starts'    => array(
						array( '', 'Monthly arrangement', 'Pay the setup fee and your monthly plan. Cancellation requires 30 days&rsquo; notice.' ),
						array( 'We waive the $500 setup fee', 'Six-month initial commitment', 'You commit to the first six months, then continue monthly with 30 days&rsquo; notice.' ),
					),
				),
				'why'       => array(
					'eyebrow' => 'What you&rsquo;re paying for',
					'heading' => 'A team working towards the same commercial goal.',
					'sub'     => 'Your plan gives you coordinated delivery across the parts of marketing that affect how buyers find, evaluate and contact your business.',
					'lead'    => 'You&rsquo;ll know:',
					'ticks'   => array(
						'What is being delivered.',
						'What we need from your team.',
						'Which measures we are tracking.',
						'What the results suggest we should do next.',
					),
					'tail'    => 'Where your sales data allows, reporting connects enquiries with opportunities and clients won.',
				),
				'faq'       => array(
					'eyebrow' => 'Frequently asked questions',
					'heading' => 'Before you choose.',
					'note'    => 'The nine that come up most often, answered in the order people ask them.',
					'qs'      => array(
						array( 'Which plan is right for us?',
							'Start with the growth audit. We look at your current presence, discuss what you want to achieve, and recommend a scope that fits. Your priorities, market and capacity matter more than company size alone.' ),
						array( 'Does every service run every month?',
							'The plan draws on the specialisms your business needs. Some work happens during setup, some runs regularly, and some becomes relevant later. Your proposal and monthly priorities explain the allocation.' ),
						array( 'Can we hire you for just one service?',
							'Yes. If you need a focused engagement, for example search, paid advertising or website conversion, we can propose a separate scope. The packages are designed for businesses that want coordinated ongoing support.' ),
						array( 'Is advertising spend included?',
							'No. Your monthly fee covers our work. Advertising spend is separate, stays in your account, and is agreed with you before campaigns launch.' ),
						array( 'Are software subscriptions included?',
							'Third-party costs such as CRM subscriptions, messaging charges, hosting and premium tools are separate where required. We identify expected costs before you agree to the work.' ),
						array( 'What happens if a channel underperforms?',
							'We investigate the cause, explain the findings, and agree the next action. That may mean improving the campaign, revising the offer or moving effort elsewhere. If the ongoing scope changes materially, we review the fee with you.' ),
						array( 'Can we change plans?',
							'Yes. We can review your plan as your goals, budget or capacity change. Any adjustment is agreed in writing, including when it takes effect and how it fits your current commitment.' ),
						array( 'Do you guarantee leads or revenue?',
							'We commit to the agreed work, measurement and regular improvement. Results also depend on your market, offer, budget, competition and sales process. We establish realistic objectives and explain the assumptions behind them.' ),
						array( 'Will there be additional charges?',
							'Your proposal lists the agreed fees, separate costs and any applicable taxes. Work outside the scope is discussed and approved before it is added.' ),
					),
				),
			),
		),
	),
);
